apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agones-sdk-clusterrole
rules:
- apiGroups: ["agones.dev"]
  resources: ["gameservers"]
  verbs: ["list", "get", "watch", "patch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create", "patch"]  # ← Add "patch" here
