apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agones-sdk-clusterrolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: agones-sdk-clusterrole
subjects:
- kind: ServiceAccount
  name: agones-sdk
  namespace: gameserver
