apiVersion: autoscaling.agones.dev/v1
kind: FleetAutoscaler
metadata:
  name: gamefleet-autoscaler
spec:
  fleetName: gamefleet
  policy:
    type: Buffer
    buffer:
      bufferSize: 1
      minReplicas: 0
      maxReplicas: 2
