apiVersion: "allocation.agones.dev/v1"
kind: GameServerAllocation
spec:
  selectors:
    - matchLabels:
        agones.dev/fleet: gamefleet
      gameServerState: Ready
      players:
        minAvailable: 1
        maxAvailable: 2